### ISSUE TITLE
Readd source code type marker to the documentation

### ISSUE THREAD

**Issue by SebastianNiemann** [Mantella/Mantella#342]
Before we fixed #324 , we had little markers on the right side of each code example, specifying the language.

The should be readded:
``` html
<div class="language">
  <span>C++</span>
</div>
```

``` css
main .language {
  position: relative;
}

main .language span {
position: absolute;
  top: 0;
  right: 0;
  z-index: 1;
  display: block;
  padding: 5px 8px;
  font-size: 12px;
  color: ...;
  background-color: ...;
  border: 1px solid ...;
  border-radius: 0 4px 0 4px;
}
```
