### ISSUE TITLE
Limit the documentation's body maximal width 

### ISSUE THREAD

**Issue by SebastianNiemann** [Mantella/Mantella#343]
Currently, the documentation stretches as far as the window/monitor allows. 

With this, images are far to width an the reading text becomes bothersome.

To fix this, we should add something like
``` css
main {
  max-width: 1200px;
}
```
